### ISSUE TITLE
from depinfo import print_dependencies does not work in 2.0.0 but does work in 1.7.0

### ISSUE THREAD

**Issue by dtmvandenberg** [Midnighter/dependency-info#11]
#### Problem description

Please explain:
When importing cobra 0.24 or 0.25 on python 3.8 you get the error "Can not find name print_dependencies in package depinfo" downgrading to 1.7.0 solves the problem. 

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
import cobra
```

```
ImportError: cannot import name 'print_dependencies' from 'depinfo'
```

### Context

<details>

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'depinfo' has no attribute 'show_versions'
```

</details>
I installed depinfo from conda-forge.

**Comment by Midnighter** [comment]
I'm working on a fix.
